// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:backendless_sdk/backendless_sdk.dart' as prefix0;
import 'package:hive/hive.dart' as prefix2;
import 'package:pickapp/dataObjects/Message.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Message',
            r'.Message',
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3, 4, 5, 12, 13],
            const <int>[14, 5, 15, 16, 17, 4, 6, 7, 8, 9, 10, 11],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({senderId, message, date, myMessage}) => b
                  ? prefix1.Message(
                      date: date,
                      message: message,
                      myMessage: myMessage,
                      senderId: senderId)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.Message.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              const prefix2.HiveType(typeId: 11),
              prefix0.reflector
            ],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'date', 32773, 0, const prefix0.Reflector(), -1,
            1, 1, null, const <Object>[const prefix2.HiveField(0)]),
        r.VariableMirrorImpl(r'message', 33797, 0, const prefix0.Reflector(),
            -1, 2, 2, null, const <Object>[const prefix2.HiveField(1)]),
        r.VariableMirrorImpl(r'myMessage', 33797, 0, const prefix0.Reflector(),
            -1, 3, 3, null, const <Object>[const prefix2.HiveField(2)]),
        r.VariableMirrorImpl(r'senderId', 32773, 0, const prefix0.Reflector(),
            -1, 2, 2, null, const <Object>[const prefix2.HiveField(3)]),
        r.MethodMirrorImpl(r'toJson', 4325378, 0, -1, 4, 5, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 131074, 0, -1, 2, 2, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 6),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 7),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 8),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 9),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 3, 10),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 3, 11),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, null, const <int>[0, 1, 2, 3],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'fromJson', 0, 0, -1, 0, 0, null, const <int>[4],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 3, 3, null, const <int>[7],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, null, null, null, null, null,
            const <int>[8], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 6, 6, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, 7, 7, null,
            const <int>[], const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'senderId', 45062, 12, const prefix0.Reflector(),
            -1, 2, 2, null, const [], null, #senderId),
        r.ParameterMirrorImpl(r'message', 45062, 12, const prefix0.Reflector(),
            -1, 2, 2, null, const [], null, #message),
        r.ParameterMirrorImpl(r'date', 45062, 12, const prefix0.Reflector(), -1,
            1, 1, null, const [], null, #date),
        r.ParameterMirrorImpl(
            r'myMessage',
            45062,
            12,
            const prefix0.Reflector(),
            -1,
            3,
            3,
            null,
            const [],
            null,
            #myMessage),
        r.ParameterMirrorImpl(r'json', 2129926, 13, const prefix0.Reflector(),
            -1, 4, 5, null, const [], null, null),
        r.ParameterMirrorImpl(r'_date', 32870, 7, const prefix0.Reflector(), -1,
            1, 1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_senderId', 32870, 11,
            const prefix0.Reflector(), -1, 2, 2, null, const [], null, null),
        r.ParameterMirrorImpl(r'other', 32774, 14, const prefix0.Reflector(),
            -1, 8, 8, null, const [], null, null),
        r.ParameterMirrorImpl(r'invocation', 32774, 15,
            const prefix0.Reflector(), -1, 9, 9, null, const [], null, null)
      ],
      <Type>[
        prefix1.Message,
        DateTime,
        String,
        bool,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        int,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'date': (dynamic instance) => instance.date,
        r'message': (dynamic instance) => instance.message,
        r'myMessage': (dynamic instance) => instance.myMessage,
        r'senderId': (dynamic instance) => instance.senderId
      },
      {
        r'date=': (dynamic instance, value) => instance.date = value,
        r'senderId=': (dynamic instance, value) => instance.senderId = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
