# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ android_production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
     # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        with:
          channel: master
      - run: flutter doctor -v

      # Checkout gallery code and get packages.
      - name: Build aab for android
        uses: actions/checkout@v2
      - run: | 
           flutter pub get
           flutter build appbundle
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: push to internal testing on play store
        uses: r0adkll/upload-google-play@v1
        with:
         serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
         packageName: com.voomcar.voomcar
         releaseFile: app/build/outputs/bundle/release/*.aab
         track: internal
         inAppUpdatePriority: 2
         userFraction: 0.33
         whatsNewDirectory: distribution/whatsnew
         mappingFile: app/build/outputs/mapping/release/mapping.txt
