# This is a basic workflow to help you get started with Actions

name: Publish Android Internal Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: upload to internal testing play store 
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.justMiles.justMiles
          releaseFiles: build/app/outputs/bundle/release/*.aab
          track: internal
          inAppUpdatePriority: 1
          whatsNewDirectory: distribution
